services:
  rabbitmq-broker:
    image: rabbitmq:4.0-management
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq-broker
    networks:
      - broker-network

  consul:
    image: hashicorp/consul:latest
    ports: 
      - 8500:8500
      - 8600:8600/udp
      - 8600:8600/tcp
    command: "agent -server -bootstrap-expect=1 -ui -data-dir=/consul/data -client=0.0.0.0"
    container_name: consul
    volumes:
      - ./consul-data:/consul/data
    networks:
      - broker-network

networks:
  broker-network:
    name: clinic
    driver: bridge
    external: true

volumes:
  consul-data: {}