services:
  auth-service-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1435:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyVeryStrongPassword1234321
      - MSSQL_PID=Developer
    volumes:
      - auth-service-db:/var/lib/mssql/data
    container_name: auth_service_db
    networks:
      - auth-network

  auth-app:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 5006:8080
      - 5016:8081
    container_name: auth_service_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - auth-service-database
    networks:
      - auth-network

volumes:
  auth-service-db:

networks:
  auth-network:
        name: clinic
        driver: bridge
        external: true