<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Offices.Core\Offices.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CQRS\Offices\Commands\UpdateOffice\" />
    <Folder Include="CQRS\Offices\Queries\GetOffices\" />
    <Folder Include="CQRS\Receptionists\Commands\" />
    <Folder Include="CQRS\Receptionists\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

</Project>
